"""initial_schema

Revision ID: 93acabb1e890
Revises: 
Create Date: 2026-05-31 11:54:18.998326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93acabb1e890'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_favorite', sa.Column('status', sa.String(length=32), nullable=False))
    op.alter_column('download_catalog', 'cover_url',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('download_tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('download_tasks', 'speed_limit',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('download_tasks', 'speed_limit',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('download_tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('download_catalog', 'cover_url',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.drop_column('catalog_favorite', 'status')
    # ### end Alembic commands ###
